### ISSUE TITLE
Weird behavior on Turbolinks page:change

### ISSUE THREAD

**Issue by jerefrer** [netguru/react_webpack_rails#102] opened 2016-06-07 13:49 UTC
Hi there,

First, thanks for the awesome gem it's been a breeze to work with so far !

We decided to add Turbolinks on a Rails 3.2.12 legacy app using react_webpack_rails@master (tried 0.4-stable first) and noticed that the React components don't get refreshed properly.

When loading the page the first time everything is rendered just fine and works as expected.

Then When we change the page using Turbolinks (no hard-refresh) then the component gets rendered (the DOM is rendered), but it's not usable. For instance in the case of a slider all the slides are rendered but the button to get to the next slide is not working nor swipe gesture.

I find this super-weird that the DOM is visible but 

I noticed that if I call `RWRhandlers._mountNodes()` by hand after switching page then the component starts to work again, but it show this warning in the console:

    warning.js?8a56:45 Warning: React attempted to reuse markup in a container but the
    checksum was invalid. This generally means that you are using server rendering and 
    the markup generated on the server was not what the client was expecting.
    React injected new markup to compensate which works but you have lost many of the
    benefits of server rendering. Instead, figure out why the markup being generated
    is different on the client or server:
     (client) r " style="position:relative;display:blo
     (server) r " style="position: relative; display: 

So although it's working it feels quite hackish.

Furthermore on another page we render a gallery using masonry and a custom lightbox, and in this case it's just not working when trying to `RWRhandlers._mountNodes()`. This time this error is displayed:

    invariant.js?4599:39 Uncaught Error: findComponentRoot(..., .0.1.$1716):
    Unable to find element. This probably means the DOM was unexpectedly mutated
    (e.g., by the browser), usually due to forgetting a <tbody> when using tables,
    nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg>
    parent. Try inspecting the child nodes of the element with React ID ``.

This error does not happen if I switch from one page with a gallery component to another page with a gallery. It happens only if I switch from a page with no gallery to a page with one.

I've been using React now and then but I'm far from confident using it so I really don't know if there are one or two issues here or where to go next to fix this situation.

Any idea ?

**Comment by mxaly** [comment] 2016-06-07 14:06
Hi @jerefrer. Looks like for some reason rwr is not handling turbolinks events properly. Can you share your turbolinks version?

**Comment by jerefrer** [comment] 2016-06-07 14:16
@mxaly It's turbolinks 2.5.3.

If I comment out the call to `RWRhandlers.handleTurbolinksEvents();` in react_integration.js.erb then when changing page the component is never rendered until I call `RWRhandlers._mountNodes()` myself. In this case it seems there is never any problem.

**Comment by jerefrer** [comment] 2016-06-07 14:21
I did jus that: add a `setTimeout` of 200ms around `RWRhandlers._mountNodes()` and it seems to be working in all cases.

From

    RWRhandlers._handleEvent(mountEvent, RWRhandlers._mountNodes);

To

    RWRhandlers._handleEvent(mountEvent, function() { setTimeout(RWRhandlers._mountNodes, 200) });

**Comment by jerefrer** [comment] 2016-06-08 07:00
@mxaly Any clue why it's not working by default ?

I like that the `setTimeout` is working but then I have two more issues.
First is to have to fork your gem and then have to maintain the fork.
Second is that I have to style the React component placeholders prior to rendering in order not to have the component "pop-up" after 200ms, for instance by giving them a fixed height.

Obviously a proper solution to this would be better !

**Comment by mxaly** [comment] 2016-06-08 08:09
@jerefrer definitely! Let's keep this open. We will look for proper solution.

**Comment by jerefrer** [comment] 2016-06-08 08:24
@mxaly Okay let me know if I can help tracking the source. I don't mind sharing the components code or pairing in a debugging session.

**Comment by jerefrer** [comment] 2016-06-10 14:44
@mxaly Something new happened. We removed the React slider we were using to go with owlCarousel, so we ended up having only one React component in the project instead of two. We didn't realize at first but it may have solved our issue: the lightbox (the only component left) is working all the time.

So maybe the bug has something to do with loading different components and replacing them.

**Comment by mxaly** [comment] 2016-06-20 09:03
@jerefrer I have tried to reproduce this but no success :( Current turbolinks events seem to be working fine. Is it possible for you to share this case somehow or it's private project?

**Comment by jerefrer** [comment] 2016-06-20 09:24
@mxaly I can't share the whole project but maybe try to make a dummy project with just what's needed to reproduce the issue.

But as I said in my last message we got rid of the issue.
Also I think maybe it was related to using old versions of everything (Rails 3.2.12, Turbolinks 2.5.3, an old version of RefineryCMS, etc.).

In light of all this, and since building a dummy project would take some time, and I don't have much, do you think it would be actually useful for you to track down this issue, or could we just close it and hope it won't happen again ?

**Comment by mxaly** [comment] 2016-06-20 09:32
We would love to support rails 3 as we are using it in legacy projects too so yes, it would be great if you can prepare the dummy app.
I know that it will take some time so let's close this issue and whenever you will have time and will for creating the dummy app, just let us know. There is no rush especially that you manage to solve it.
Thanks in advance @jerefrer :)

**Closed by mxaly** 2016-06-20 09:32 UTC
